//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uppgift2_Konsol.Uppgift2_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private int ageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Grupp7", ConfigurationName="Uppgift2_ServiceReference.Uppgift2_ServiceSoap")]
    public interface Uppgift2_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllPersonsResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPersons", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse GetAllPersons(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPersons", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse> GetAllPersonsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPersons", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequestBody Body;
        
        public GetAllPersonsRequest() {
        }
        
        public GetAllPersonsRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPersonsRequestBody {
        
        public GetAllPersonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPersonsResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponseBody Body;
        
        public GetAllPersonsResponse() {
        }
        
        public GetAllPersonsResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Person[] GetAllPersonsResult;
        
        public GetAllPersonsResponseBody() {
        }
        
        public GetAllPersonsResponseBody(Uppgift2_Konsol.Uppgift2_ServiceReference.Person[] GetAllPersonsResult) {
            this.GetAllPersonsResult = GetAllPersonsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Uppgift2_ServiceSoapChannel : Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Uppgift2_ServiceSoapClient : System.ServiceModel.ClientBase<Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap>, Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap {
        
        public Uppgift2_ServiceSoapClient() {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Uppgift2_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPersons(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest request) {
            return base.Channel.GetAllPersons(request);
        }
        
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Person[] GetAllPersons() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPersons(inValue);
            return retVal.Body.GetAllPersonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPersonsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest request) {
            return base.Channel.GetAllPersonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse> GetAllPersonsAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPersonsAsync(inValue);
        }
    }
}
