//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uppgift2_Konsol.Uppgift2_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private int ageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AboutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndustryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession FieldOfProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose[] UserLocationPurposesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Profession {
            get {
                return this.ProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionField, value) != true)) {
                    this.ProfessionField = value;
                    this.RaisePropertyChanged("Profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string About {
            get {
                return this.AboutField;
            }
            set {
                if ((object.ReferenceEquals(this.AboutField, value) != true)) {
                    this.AboutField = value;
                    this.RaisePropertyChanged("About");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Industry {
            get {
                return this.IndustryField;
            }
            set {
                if ((object.ReferenceEquals(this.IndustryField, value) != true)) {
                    this.IndustryField = value;
                    this.RaisePropertyChanged("Industry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession FieldOfProfession {
            get {
                return this.FieldOfProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldOfProfessionField, value) != true)) {
                    this.FieldOfProfessionField = value;
                    this.RaisePropertyChanged("FieldOfProfession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose[] UserLocationPurposes {
            get {
                return this.UserLocationPurposesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLocationPurposesField, value) != true)) {
                    this.UserLocationPurposesField = value;
                    this.RaisePropertyChanged("UserLocationPurposes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldOfProfession", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class FieldOfProfession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndustryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Industry {
            get {
                return this.IndustryField;
            }
            set {
                if ((object.ReferenceEquals(this.IndustryField, value) != true)) {
                    this.IndustryField = value;
                    this.RaisePropertyChanged("Industry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLocationPurpose", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class UserLocationPurpose : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose PurposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposetypeField;
        
        private System.Nullable<System.DateTime> FromDateField;
        
        private System.Nullable<System.DateTime> ToDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose Purpose {
            get {
                return this.PurposeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeField, value) != true)) {
                    this.PurposeField = value;
                    this.RaisePropertyChanged("Purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Purposetype {
            get {
                return this.PurposetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposetypeField, value) != true)) {
                    this.PurposetypeField = value;
                    this.RaisePropertyChanged("Purposetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((this.ToDateField.Equals(value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose[] UserLocationPurposesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose[] UserLocationPurposes {
            get {
                return this.UserLocationPurposesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLocationPurposesField, value) != true)) {
                    this.UserLocationPurposesField = value;
                    this.RaisePropertyChanged("UserLocationPurposes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Purpose", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Purpose : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose[] UserLocationPurposesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PurposeType {
            get {
                return this.PurposeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeTypeField, value) != true)) {
                    this.PurposeTypeField = value;
                    this.RaisePropertyChanged("PurposeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose[] UserLocationPurposes {
            get {
                return this.UserLocationPurposesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLocationPurposesField, value) != true)) {
                    this.UserLocationPurposesField = value;
                    this.RaisePropertyChanged("UserLocationPurposes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Grupp7", ConfigurationName="Uppgift2_ServiceReference.Uppgift2_ServiceSoap")]
    public interface Uppgift2_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllPersonsResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPersons", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse GetAllPersons(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPersons", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse> GetAllPersonsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest request);
        
        // CODEGEN: Generating message contract since element name GetUsersResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetUsers", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersResponse GetUsers(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersResponse> GetUsersAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since element name GetPurposesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetPurposes", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesResponse GetPurposes(Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetPurposes", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesResponse> GetPurposesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequest request);
        
        // CODEGEN: Generating message contract since element name GetLocationsResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetLocations", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsResponse GetLocations(Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetLocations", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsResponse> GetLocationsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserLocationPurposesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetUserLocationPurposes", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesResponse GetUserLocationPurposes(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetUserLocationPurposes", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesResponse> GetUserLocationPurposesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequest request);
        
        // CODEGEN: Generating message contract since element name GetFieldOfProfessionsResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetFieldOfProfessions", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsResponse GetFieldOfProfessions(Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetFieldOfProfessions", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsResponse> GetFieldOfProfessionsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPersons", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequestBody Body;
        
        public GetAllPersonsRequest() {
        }
        
        public GetAllPersonsRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPersonsRequestBody {
        
        public GetAllPersonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPersonsResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponseBody Body;
        
        public GetAllPersonsResponse() {
        }
        
        public GetAllPersonsResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Person[] GetAllPersonsResult;
        
        public GetAllPersonsResponseBody() {
        }
        
        public GetAllPersonsResponseBody(Uppgift2_Konsol.Uppgift2_ServiceReference.Person[] GetAllPersonsResult) {
            this.GetAllPersonsResult = GetAllPersonsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.User[] GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(Uppgift2_Konsol.Uppgift2_ServiceReference.User[] GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPurposesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPurposes", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequestBody Body;
        
        public GetPurposesRequest() {
        }
        
        public GetPurposesRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPurposesRequestBody {
        
        public GetPurposesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPurposesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPurposesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesResponseBody Body;
        
        public GetPurposesResponse() {
        }
        
        public GetPurposesResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetPurposesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose[] GetPurposesResult;
        
        public GetPurposesResponseBody() {
        }
        
        public GetPurposesResponseBody(Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose[] GetPurposesResult) {
            this.GetPurposesResult = GetPurposesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLocations", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequestBody Body;
        
        public GetLocationsRequest() {
        }
        
        public GetLocationsRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLocationsRequestBody {
        
        public GetLocationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLocationsResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsResponseBody Body;
        
        public GetLocationsResponse() {
        }
        
        public GetLocationsResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetLocationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Location[] GetLocationsResult;
        
        public GetLocationsResponseBody() {
        }
        
        public GetLocationsResponseBody(Uppgift2_Konsol.Uppgift2_ServiceReference.Location[] GetLocationsResult) {
            this.GetLocationsResult = GetLocationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserLocationPurposesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserLocationPurposes", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequestBody Body;
        
        public GetUserLocationPurposesRequest() {
        }
        
        public GetUserLocationPurposesRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUserLocationPurposesRequestBody {
        
        public GetUserLocationPurposesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserLocationPurposesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserLocationPurposesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesResponseBody Body;
        
        public GetUserLocationPurposesResponse() {
        }
        
        public GetUserLocationPurposesResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetUserLocationPurposesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose[] GetUserLocationPurposesResult;
        
        public GetUserLocationPurposesResponseBody() {
        }
        
        public GetUserLocationPurposesResponseBody(Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose[] GetUserLocationPurposesResult) {
            this.GetUserLocationPurposesResult = GetUserLocationPurposesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFieldOfProfessionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFieldOfProfessions", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequestBody Body;
        
        public GetFieldOfProfessionsRequest() {
        }
        
        public GetFieldOfProfessionsRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFieldOfProfessionsRequestBody {
        
        public GetFieldOfProfessionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFieldOfProfessionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFieldOfProfessionsResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsResponseBody Body;
        
        public GetFieldOfProfessionsResponse() {
        }
        
        public GetFieldOfProfessionsResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetFieldOfProfessionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession[] GetFieldOfProfessionsResult;
        
        public GetFieldOfProfessionsResponseBody() {
        }
        
        public GetFieldOfProfessionsResponseBody(Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession[] GetFieldOfProfessionsResult) {
            this.GetFieldOfProfessionsResult = GetFieldOfProfessionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Uppgift2_ServiceSoapChannel : Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Uppgift2_ServiceSoapClient : System.ServiceModel.ClientBase<Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap>, Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap {
        
        public Uppgift2_ServiceSoapClient() {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Uppgift2_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPersons(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest request) {
            return base.Channel.GetAllPersons(request);
        }
        
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Person[] GetAllPersons() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPersons(inValue);
            return retVal.Body.GetAllPersonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPersonsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest request) {
            return base.Channel.GetAllPersonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsResponse> GetAllPersonsAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPersonsRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPersonsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetUsers(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public Uppgift2_Konsol.Uppgift2_ServiceReference.User[] GetUsers() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetUsersAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersResponse> GetUsersAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetUsersRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetPurposes(Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequest request) {
            return base.Channel.GetPurposes(request);
        }
        
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose[] GetPurposes() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetPurposes(inValue);
            return retVal.Body.GetPurposesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetPurposesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequest request) {
            return base.Channel.GetPurposesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesResponse> GetPurposesAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetPurposesRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetPurposesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetLocations(Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequest request) {
            return base.Channel.GetLocations(request);
        }
        
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Location[] GetLocations() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetLocations(inValue);
            return retVal.Body.GetLocationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetLocationsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequest request) {
            return base.Channel.GetLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsResponse> GetLocationsAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetLocationsRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetLocationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetUserLocationPurposes(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequest request) {
            return base.Channel.GetUserLocationPurposes(request);
        }
        
        public Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose[] GetUserLocationPurposes() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetUserLocationPurposes(inValue);
            return retVal.Body.GetUserLocationPurposesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetUserLocationPurposesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequest request) {
            return base.Channel.GetUserLocationPurposesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesResponse> GetUserLocationPurposesAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetUserLocationPurposesRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetUserLocationPurposesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetFieldOfProfessions(Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequest request) {
            return base.Channel.GetFieldOfProfessions(request);
        }
        
        public Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession[] GetFieldOfProfessions() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetFieldOfProfessions(inValue);
            return retVal.Body.GetFieldOfProfessionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetFieldOfProfessionsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequest request) {
            return base.Channel.GetFieldOfProfessionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsResponse> GetFieldOfProfessionsAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetFieldOfProfessionsRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetFieldOfProfessionsAsync(inValue);
        }
    }
}
