//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uppgift2_Konsol.Uppgift2_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AboutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndustryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession FieldOfProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose> UserLocationPurposesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Match> MatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Message> MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Profession {
            get {
                return this.ProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionField, value) != true)) {
                    this.ProfessionField = value;
                    this.RaisePropertyChanged("Profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string About {
            get {
                return this.AboutField;
            }
            set {
                if ((object.ReferenceEquals(this.AboutField, value) != true)) {
                    this.AboutField = value;
                    this.RaisePropertyChanged("About");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Industry {
            get {
                return this.IndustryField;
            }
            set {
                if ((object.ReferenceEquals(this.IndustryField, value) != true)) {
                    this.IndustryField = value;
                    this.RaisePropertyChanged("Industry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession FieldOfProfession {
            get {
                return this.FieldOfProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldOfProfessionField, value) != true)) {
                    this.FieldOfProfessionField = value;
                    this.RaisePropertyChanged("FieldOfProfession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose> UserLocationPurposes {
            get {
                return this.UserLocationPurposesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLocationPurposesField, value) != true)) {
                    this.UserLocationPurposesField = value;
                    this.RaisePropertyChanged("UserLocationPurposes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Match> Matches {
            get {
                return this.MatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchesField, value) != true)) {
                    this.MatchesField = value;
                    this.RaisePropertyChanged("Matches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Message> Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldOfProfession", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class FieldOfProfession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndustryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.User> UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Industry {
            get {
                return this.IndustryField;
            }
            set {
                if ((object.ReferenceEquals(this.IndustryField, value) != true)) {
                    this.IndustryField = value;
                    this.RaisePropertyChanged("Industry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.User> Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLocationPurpose", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class UserLocationPurpose : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose PurposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposetypeField;
        
        private System.DateTime FromDateField;
        
        private System.DateTime ToDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose Purpose {
            get {
                return this.PurposeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeField, value) != true)) {
                    this.PurposeField = value;
                    this.RaisePropertyChanged("Purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Purposetype {
            get {
                return this.PurposetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposetypeField, value) != true)) {
                    this.PurposetypeField = value;
                    this.RaisePropertyChanged("Purposetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((this.ToDateField.Equals(value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MatchUsername {
            get {
                return this.MatchUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchUsernameField, value) != true)) {
                    this.MatchUsernameField = value;
                    this.RaisePropertyChanged("MatchUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecieverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Uppgift2_Konsol.Uppgift2_ServiceReference.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Reciever {
            get {
                return this.RecieverField;
            }
            set {
                if ((object.ReferenceEquals(this.RecieverField, value) != true)) {
                    this.RecieverField = value;
                    this.RaisePropertyChanged("Reciever");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose> UserLocationPurposesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose> UserLocationPurposes {
            get {
                return this.UserLocationPurposesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLocationPurposesField, value) != true)) {
                    this.UserLocationPurposesField = value;
                    this.RaisePropertyChanged("UserLocationPurposes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Purpose", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Purpose : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose> UserLocationPurposesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PurposeType {
            get {
                return this.PurposeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeTypeField, value) != true)) {
                    this.PurposeTypeField = value;
                    this.RaisePropertyChanged("PurposeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose> UserLocationPurposes {
            get {
                return this.UserLocationPurposesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLocationPurposesField, value) != true)) {
                    this.UserLocationPurposesField = value;
                    this.RaisePropertyChanged("UserLocationPurposes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Grupp7", ConfigurationName="Uppgift2_ServiceReference.Uppgift2_ServiceSoap")]
    public interface Uppgift2_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllUsers", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersResponse GetAllUsers(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersResponse> GetAllUsersAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllPurposesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPurposes", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesResponse GetAllPurposes(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPurposes", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesResponse> GetAllPurposesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllLocationsResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllLocations", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsResponse GetAllLocations(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllLocations", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsResponse> GetAllLocationsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUserLocationPurposesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllUserLocationPurposes", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesResponse GetAllUserLocationPurposes(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllUserLocationPurposes", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesResponse> GetAllUserLocationPurposesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllFieldOfProfessionsResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllFieldOfProfessions", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse GetAllFieldOfProfessions(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllFieldOfProfessions", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse> GetAllFieldOfProfessionsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllMessagesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllMessages", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesResponse GetAllMessages(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesResponse> GetAllMessagesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllMatchesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllMatches", ReplyAction="*")]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesResponse GetAllMatches(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllMatches", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesResponse> GetAllMatchesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.User> GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.User> GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPurposesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPurposes", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequestBody Body;
        
        public GetAllPurposesRequest() {
        }
        
        public GetAllPurposesRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPurposesRequestBody {
        
        public GetAllPurposesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPurposesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPurposesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesResponseBody Body;
        
        public GetAllPurposesResponse() {
        }
        
        public GetAllPurposesResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllPurposesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose> GetAllPurposesResult;
        
        public GetAllPurposesResponseBody() {
        }
        
        public GetAllPurposesResponseBody(System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose> GetAllPurposesResult) {
            this.GetAllPurposesResult = GetAllPurposesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLocationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLocations", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequestBody Body;
        
        public GetAllLocationsRequest() {
        }
        
        public GetAllLocationsRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllLocationsRequestBody {
        
        public GetAllLocationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLocationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLocationsResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsResponseBody Body;
        
        public GetAllLocationsResponse() {
        }
        
        public GetAllLocationsResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllLocationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Location> GetAllLocationsResult;
        
        public GetAllLocationsResponseBody() {
        }
        
        public GetAllLocationsResponseBody(System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Location> GetAllLocationsResult) {
            this.GetAllLocationsResult = GetAllLocationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserLocationPurposesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUserLocationPurposes", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequestBody Body;
        
        public GetAllUserLocationPurposesRequest() {
        }
        
        public GetAllUserLocationPurposesRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUserLocationPurposesRequestBody {
        
        public GetAllUserLocationPurposesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserLocationPurposesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUserLocationPurposesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesResponseBody Body;
        
        public GetAllUserLocationPurposesResponse() {
        }
        
        public GetAllUserLocationPurposesResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllUserLocationPurposesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose> GetAllUserLocationPurposesResult;
        
        public GetAllUserLocationPurposesResponseBody() {
        }
        
        public GetAllUserLocationPurposesResponseBody(System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose> GetAllUserLocationPurposesResult) {
            this.GetAllUserLocationPurposesResult = GetAllUserLocationPurposesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFieldOfProfessionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFieldOfProfessions", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequestBody Body;
        
        public GetAllFieldOfProfessionsRequest() {
        }
        
        public GetAllFieldOfProfessionsRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllFieldOfProfessionsRequestBody {
        
        public GetAllFieldOfProfessionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFieldOfProfessionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFieldOfProfessionsResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponseBody Body;
        
        public GetAllFieldOfProfessionsResponse() {
        }
        
        public GetAllFieldOfProfessionsResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllFieldOfProfessionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession> GetAllFieldOfProfessionsResult;
        
        public GetAllFieldOfProfessionsResponseBody() {
        }
        
        public GetAllFieldOfProfessionsResponseBody(System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession> GetAllFieldOfProfessionsResult) {
            this.GetAllFieldOfProfessionsResult = GetAllFieldOfProfessionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMessages", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequestBody Body;
        
        public GetAllMessagesRequest() {
        }
        
        public GetAllMessagesRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMessagesRequestBody {
        
        public GetAllMessagesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMessagesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesResponseBody Body;
        
        public GetAllMessagesResponse() {
        }
        
        public GetAllMessagesResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Message> GetAllMessagesResult;
        
        public GetAllMessagesResponseBody() {
        }
        
        public GetAllMessagesResponseBody(System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Message> GetAllMessagesResult) {
            this.GetAllMessagesResult = GetAllMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMatchesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMatches", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequestBody Body;
        
        public GetAllMatchesRequest() {
        }
        
        public GetAllMatchesRequest(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMatchesRequestBody {
        
        public GetAllMatchesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMatchesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMatchesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesResponseBody Body;
        
        public GetAllMatchesResponse() {
        }
        
        public GetAllMatchesResponse(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllMatchesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Match> GetAllMatchesResult;
        
        public GetAllMatchesResponseBody() {
        }
        
        public GetAllMatchesResponseBody(System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Match> GetAllMatchesResult) {
            this.GetAllMatchesResult = GetAllMatchesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Uppgift2_ServiceSoapChannel : Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Uppgift2_ServiceSoapClient : System.ServiceModel.ClientBase<Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap>, Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap {
        
        public Uppgift2_ServiceSoapClient() {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Uppgift2_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllUsers(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.User> GetAllUsers() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllUsersAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersResponse> GetAllUsersAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUsersRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPurposes(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequest request) {
            return base.Channel.GetAllPurposes(request);
        }
        
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Purpose> GetAllPurposes() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPurposes(inValue);
            return retVal.Body.GetAllPurposesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPurposesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequest request) {
            return base.Channel.GetAllPurposesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesResponse> GetAllPurposesAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllPurposesRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPurposesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllLocations(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequest request) {
            return base.Channel.GetAllLocations(request);
        }
        
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Location> GetAllLocations() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllLocations(inValue);
            return retVal.Body.GetAllLocationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllLocationsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequest request) {
            return base.Channel.GetAllLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsResponse> GetAllLocationsAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllLocationsRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllLocationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllUserLocationPurposes(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequest request) {
            return base.Channel.GetAllUserLocationPurposes(request);
        }
        
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.UserLocationPurpose> GetAllUserLocationPurposes() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllUserLocationPurposes(inValue);
            return retVal.Body.GetAllUserLocationPurposesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllUserLocationPurposesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequest request) {
            return base.Channel.GetAllUserLocationPurposesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesResponse> GetAllUserLocationPurposesAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllUserLocationPurposesRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllUserLocationPurposesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllFieldOfProfessions(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest request) {
            return base.Channel.GetAllFieldOfProfessions(request);
        }
        
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.FieldOfProfession> GetAllFieldOfProfessions() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllFieldOfProfessions(inValue);
            return retVal.Body.GetAllFieldOfProfessionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllFieldOfProfessionsAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest request) {
            return base.Channel.GetAllFieldOfProfessionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse> GetAllFieldOfProfessionsAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllFieldOfProfessionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllMessages(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequest request) {
            return base.Channel.GetAllMessages(request);
        }
        
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Message> GetAllMessages() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllMessages(inValue);
            return retVal.Body.GetAllMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllMessagesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequest request) {
            return base.Channel.GetAllMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesResponse> GetAllMessagesAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMessagesRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesResponse Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllMatches(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequest request) {
            return base.Channel.GetAllMatches(request);
        }
        
        public System.Collections.Generic.List<Uppgift2_Konsol.Uppgift2_ServiceReference.Match> GetAllMatches() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequestBody();
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesResponse retVal = ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllMatches(inValue);
            return retVal.Body.GetAllMatchesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesResponse> Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllMatchesAsync(Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequest request) {
            return base.Channel.GetAllMatchesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesResponse> GetAllMatchesAsync() {
            Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequest inValue = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequest();
            inValue.Body = new Uppgift2_Konsol.Uppgift2_ServiceReference.GetAllMatchesRequestBody();
            return ((Uppgift2_Konsol.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllMatchesAsync(inValue);
        }
    }
}
