//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uppgift3_Forms.Uppgift3_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeRelative", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class EmployeeRelative : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmployeeNumber {
            get {
                return this.EmployeeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNumberField, value) != true)) {
                    this.EmployeeNumberField = value;
                    this.RaisePropertyChanged("EmployeeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Grupp7", ConfigurationName="Uppgift3_ServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/HelloWorld", ReplyAction="*")]
        Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldResponse HelloWorld(Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldResponse> HelloWorldAsync(Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetEmployees", ReplyAction="*")]
        Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesResponse GetEmployees(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesResponse> GetEmployeesAsync(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeeRelativesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetEmployeeRelatives", ReplyAction="*")]
        Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesResponse GetEmployeeRelatives(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetEmployeeRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesResponse> GetEmployeeRelativesAsync(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="Grupp7", Order=0)]
        public Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="Grupp7", Order=0)]
        public Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="Grupp7", Order=0)]
        public Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift3_Forms.Uppgift3_ServiceReference.Employee> GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(System.Collections.Generic.List<Uppgift3_Forms.Uppgift3_ServiceReference.Employee> GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeRelatives", Namespace="Grupp7", Order=0)]
        public Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequestBody Body;
        
        public GetEmployeeRelativesRequest() {
        }
        
        public GetEmployeeRelativesRequest(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeRelativesRequestBody {
        
        public GetEmployeeRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeRelativesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesResponseBody Body;
        
        public GetEmployeeRelativesResponse() {
        }
        
        public GetEmployeeRelativesResponse(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetEmployeeRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift3_Forms.Uppgift3_ServiceReference.EmployeeRelative> GetEmployeeRelativesResult;
        
        public GetEmployeeRelativesResponseBody() {
        }
        
        public GetEmployeeRelativesResponseBody(System.Collections.Generic.List<Uppgift3_Forms.Uppgift3_ServiceReference.EmployeeRelative> GetEmployeeRelativesResult) {
            this.GetEmployeeRelativesResult = GetEmployeeRelativesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap>, Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldResponse Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap.HelloWorld(Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequest inValue = new Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequest();
            inValue.Body = new Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequestBody();
            Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldResponse retVal = ((Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldResponse> Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap.HelloWorldAsync(Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequest inValue = new Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequest();
            inValue.Body = new Uppgift3_Forms.Uppgift3_ServiceReference.HelloWorldRequestBody();
            return ((Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesResponse Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap.GetEmployees(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public System.Collections.Generic.List<Uppgift3_Forms.Uppgift3_ServiceReference.Employee> GetEmployees() {
            Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequest inValue = new Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequest();
            inValue.Body = new Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequestBody();
            Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesResponse retVal = ((Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesResponse> Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap.GetEmployeesAsync(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesResponse> GetEmployeesAsync() {
            Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequest inValue = new Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequest();
            inValue.Body = new Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeesRequestBody();
            return ((Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesResponse Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap.GetEmployeeRelatives(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequest request) {
            return base.Channel.GetEmployeeRelatives(request);
        }
        
        public System.Collections.Generic.List<Uppgift3_Forms.Uppgift3_ServiceReference.EmployeeRelative> GetEmployeeRelatives() {
            Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequest inValue = new Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequest();
            inValue.Body = new Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequestBody();
            Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesResponse retVal = ((Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap)(this)).GetEmployeeRelatives(inValue);
            return retVal.Body.GetEmployeeRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesResponse> Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap.GetEmployeeRelativesAsync(Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequest request) {
            return base.Channel.GetEmployeeRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesResponse> GetEmployeeRelativesAsync() {
            Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequest inValue = new Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequest();
            inValue.Body = new Uppgift3_Forms.Uppgift3_ServiceReference.GetEmployeeRelativesRequestBody();
            return ((Uppgift3_Forms.Uppgift3_ServiceReference.ServiceSoap)(this)).GetEmployeeRelativesAsync(inValue);
        }
    }
}
