//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uppgift2_Forms.Uppgift2_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="Grupp7")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private int ageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="Grupp7", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Grupp7", ConfigurationName="Uppgift2_ServiceReference.Uppgift2_ServiceSoap")]
    public interface Uppgift2_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllPersonsResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPersons", ReplyAction="*")]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsResponse GetAllPersons(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPersons", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsResponse> GetAllPersonsAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllUsers", ReplyAction="*")]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersResponse GetAllUsers(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersResponse> GetAllUsersAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllPurposesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPurposes", ReplyAction="*")]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesResponse GetAllPurposes(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllPurposes", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesResponse> GetAllPurposesAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequest request);
        
        // CODEGEN: Generating message contract since element name GetLocationsResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetLocations", ReplyAction="*")]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsResponse GetLocations(Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetLocations", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsResponse> GetLocationsAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserLocationPurposesResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetUserLocationPurposes", ReplyAction="*")]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesResponse GetUserLocationPurposes(Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetUserLocationPurposes", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesResponse> GetUserLocationPurposesAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllFieldOfProfessionsResult from namespace Grupp7 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllFieldOfProfessions", ReplyAction="*")]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse GetAllFieldOfProfessions(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Grupp7/GetAllFieldOfProfessions", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse> GetAllFieldOfProfessionsAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPersons", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequestBody Body;
        
        public GetAllPersonsRequest() {
        }
        
        public GetAllPersonsRequest(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPersonsRequestBody {
        
        public GetAllPersonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPersonsResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsResponseBody Body;
        
        public GetAllPersonsResponse() {
        }
        
        public GetAllPersonsResponse(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.Person[] GetAllPersonsResult;
        
        public GetAllPersonsResponseBody() {
        }
        
        public GetAllPersonsResponseBody(Uppgift2_Forms.Uppgift2_ServiceReference.Person[] GetAllPersonsResult) {
            this.GetAllPersonsResult = GetAllPersonsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPurposesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPurposes", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequestBody Body;
        
        public GetAllPurposesRequest() {
        }
        
        public GetAllPurposesRequest(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPurposesRequestBody {
        
        public GetAllPurposesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPurposesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPurposesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesResponseBody Body;
        
        public GetAllPurposesResponse() {
        }
        
        public GetAllPurposesResponse(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllPurposesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetAllPurposesResult;
        
        public GetAllPurposesResponseBody() {
        }
        
        public GetAllPurposesResponseBody(Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetAllPurposesResult) {
            this.GetAllPurposesResult = GetAllPurposesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLocations", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequestBody Body;
        
        public GetLocationsRequest() {
        }
        
        public GetLocationsRequest(Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLocationsRequestBody {
        
        public GetLocationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLocationsResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsResponseBody Body;
        
        public GetLocationsResponse() {
        }
        
        public GetLocationsResponse(Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetLocationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetLocationsResult;
        
        public GetLocationsResponseBody() {
        }
        
        public GetLocationsResponseBody(Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetLocationsResult) {
            this.GetLocationsResult = GetLocationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserLocationPurposesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserLocationPurposes", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequestBody Body;
        
        public GetUserLocationPurposesRequest() {
        }
        
        public GetUserLocationPurposesRequest(Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUserLocationPurposesRequestBody {
        
        public GetUserLocationPurposesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserLocationPurposesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserLocationPurposesResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesResponseBody Body;
        
        public GetUserLocationPurposesResponse() {
        }
        
        public GetUserLocationPurposesResponse(Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetUserLocationPurposesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetUserLocationPurposesResult;
        
        public GetUserLocationPurposesResponseBody() {
        }
        
        public GetUserLocationPurposesResponseBody(Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetUserLocationPurposesResult) {
            this.GetUserLocationPurposesResult = GetUserLocationPurposesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFieldOfProfessionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFieldOfProfessions", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequestBody Body;
        
        public GetAllFieldOfProfessionsRequest() {
        }
        
        public GetAllFieldOfProfessionsRequest(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllFieldOfProfessionsRequestBody {
        
        public GetAllFieldOfProfessionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFieldOfProfessionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFieldOfProfessionsResponse", Namespace="Grupp7", Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponseBody Body;
        
        public GetAllFieldOfProfessionsResponse() {
        }
        
        public GetAllFieldOfProfessionsResponse(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Grupp7")]
    public partial class GetAllFieldOfProfessionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetAllFieldOfProfessionsResult;
        
        public GetAllFieldOfProfessionsResponseBody() {
        }
        
        public GetAllFieldOfProfessionsResponseBody(Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetAllFieldOfProfessionsResult) {
            this.GetAllFieldOfProfessionsResult = GetAllFieldOfProfessionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Uppgift2_ServiceSoapChannel : Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Uppgift2_ServiceSoapClient : System.ServiceModel.ClientBase<Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap>, Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap {
        
        public Uppgift2_ServiceSoapClient() {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Uppgift2_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Uppgift2_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsResponse Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPersons(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequest request) {
            return base.Channel.GetAllPersons(request);
        }
        
        public Uppgift2_Forms.Uppgift2_ServiceReference.Person[] GetAllPersons() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequestBody();
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsResponse retVal = ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPersons(inValue);
            return retVal.Body.GetAllPersonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsResponse> Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPersonsAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequest request) {
            return base.Channel.GetAllPersonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsResponse> GetAllPersonsAsync() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPersonsRequestBody();
            return ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPersonsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersResponse Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllUsers(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetAllUsers() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequestBody();
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersResponse retVal = ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersResponse> Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllUsersAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersResponse> GetAllUsersAsync() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllUsersRequestBody();
            return ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesResponse Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPurposes(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequest request) {
            return base.Channel.GetAllPurposes(request);
        }
        
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetAllPurposes() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequestBody();
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesResponse retVal = ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPurposes(inValue);
            return retVal.Body.GetAllPurposesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesResponse> Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllPurposesAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequest request) {
            return base.Channel.GetAllPurposesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesResponse> GetAllPurposesAsync() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllPurposesRequestBody();
            return ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllPurposesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsResponse Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetLocations(Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequest request) {
            return base.Channel.GetLocations(request);
        }
        
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetLocations() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequestBody();
            Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsResponse retVal = ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetLocations(inValue);
            return retVal.Body.GetLocationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsResponse> Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetLocationsAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequest request) {
            return base.Channel.GetLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsResponse> GetLocationsAsync() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetLocationsRequestBody();
            return ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetLocationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesResponse Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetUserLocationPurposes(Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequest request) {
            return base.Channel.GetUserLocationPurposes(request);
        }
        
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetUserLocationPurposes() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequestBody();
            Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesResponse retVal = ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetUserLocationPurposes(inValue);
            return retVal.Body.GetUserLocationPurposesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesResponse> Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetUserLocationPurposesAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequest request) {
            return base.Channel.GetUserLocationPurposesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesResponse> GetUserLocationPurposesAsync() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetUserLocationPurposesRequestBody();
            return ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetUserLocationPurposesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllFieldOfProfessions(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest request) {
            return base.Channel.GetAllFieldOfProfessions(request);
        }
        
        public Uppgift2_Forms.Uppgift2_ServiceReference.ArrayOfAnyType GetAllFieldOfProfessions() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequestBody();
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse retVal = ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllFieldOfProfessions(inValue);
            return retVal.Body.GetAllFieldOfProfessionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse> Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap.GetAllFieldOfProfessionsAsync(Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest request) {
            return base.Channel.GetAllFieldOfProfessionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsResponse> GetAllFieldOfProfessionsAsync() {
            Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest inValue = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequest();
            inValue.Body = new Uppgift2_Forms.Uppgift2_ServiceReference.GetAllFieldOfProfessionsRequestBody();
            return ((Uppgift2_Forms.Uppgift2_ServiceReference.Uppgift2_ServiceSoap)(this)).GetAllFieldOfProfessionsAsync(inValue);
        }
    }
}
